#!/bin/bash

version=`svn info | awk -v ver="UNKNOWN" -F ":" '/R?vision/ { ver=$2 } END { print ver }' | tr -d " "`

if [ $version = 'UNKNOWN' ] ; then
  version=$(git rev-parse HEAD)
fi

if [ -z $version ] ; then
  version=UNKNOWN
fi 

filename=version.ml
prefix=$1

echo "Generating version information in file \"${filename}\" ..."

echo "" > src/${filename}
echo "(* Version file generated by Oasis *)" >> src/${filename}
echo "" >> src/${filename}
echo "let number = \"${version}\"" >> src/${filename}
echo "version number: ${version}"
echo "" >> src/${filename}
echo "let prefix = \"${prefix}\"" >> src/${filename}
echo "installation path prefix: ${prefix}"
echo "... done"
