/* C code generated by lustrec
   Version number 1.1-Unversioned directory
   Code is C99 compliant
   Using (double) floating-point numbers */
   
#ifndef _CONV
#define _CONV

/* Imports standard library */
#include "/Users/Teme/Documents/GitHub/lustrec/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Structs declarations */

/* Nodes declarations */
extern double int_to_real (int in1
                           );

extern int real_to_int (double in1
                        );


#endif

