/* C code generated by lustrec
   Version number 1.1-Unversioned directory
   Code is C99 compliant
   Using MPFR multi-precision numbers */
   
#ifndef _MPFR_LUSTRE
#define _MPFR_LUSTRE

/* Imports standard library */
#include <mpfr.h>
#include "/Users/Teme/Documents/GitHub/lustrec/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Global initialization declaration */
extern void MPFR_LUSTRE_INIT ();

/* Global clear declaration */
extern void MPFR_LUSTRE_CLEAR ();

/* Structs declarations */

/* Nodes declarations */
extern void MPFRNeq_step (mpfr_t i1, mpfr_t i2, 
                          _Bool (*out)
                          );

extern void MPFREq_step (mpfr_t i1, mpfr_t i2, 
                         _Bool (*out)
                         );

extern void MPFRGt_step (mpfr_t i1, mpfr_t i2, 
                         _Bool (*out)
                         );

extern void MPFRGe_step (mpfr_t i1, mpfr_t i2, 
                         _Bool (*out)
                         );

extern void MPFRLt_step (mpfr_t i1, mpfr_t i2, 
                         _Bool (*out)
                         );

extern void MPFRLe_step (mpfr_t i1, mpfr_t i2, 
                         _Bool (*out)
                         );

extern void MPFRDiv_step (mpfr_t i1, mpfr_t i2, 
                          mpfr_t out
                          );

extern void MPFRTimes_step (mpfr_t i1, mpfr_t i2, 
                            mpfr_t out
                            );

extern void MPFRMinus_step (mpfr_t i1, mpfr_t i2, 
                            mpfr_t out
                            );

extern void MPFRPlus_step (mpfr_t i1, mpfr_t i2, 
                           mpfr_t out
                           );

extern void MPFRUminus_step (mpfr_t i, 
                             mpfr_t out
                             );


#endif

